site_name: 2020_5EI_Team6
nav:
    - 'Protocol Specification': 'PCP-Min.md'

    - 'Initial protocol draft idea': 'PCP.md'
    - 'Vision Statement': 'process/visionstatement.md'

    - 'Software Requirements Specification': 'process/srs.md'
    - 'Software Project Management Plan': 'process/spmp.md'
    - 'Project Success Criteria': 'process/projectsuccesscriteria.md'
    
    - 'Memo of Understanding': 'process/memoofunderstanding.md'
    - 'Project Status Report': 'process/statusreport.md'
    - 'Project Closure Report': 'process/closurereport.md'
    - 'Project Release Plan': 'process/releaseplan.md'
    
    - 'Project Model Canvas': 'img/Project_Model_Canvas.pdf'
    - 'Business Model Canvas': 'img/business_model_canvas.pdf'

    - 'Architecture': 'product/architecture.md'
    - 'Coding Standards': 'product/codingstandards.md'
    - 'System Documentation': 'product/systemdocumentation.md'
    - 'Testing Specifications': 'product/testingspecifications.md'
    - 'User Guide': 'product/usageguide.md'
   

use_directory_urls: true
theme:
    name: readthedocs
