graph BT

01(client) --group--- 000
02(client) --group--- 000
03(client) --group--- 000

02 --peer-to-peer--- 10
11 --peer-to-peer--- 12

10(client) --group--- 010
11(client) --group--- 010
12(client) --group--- 010


000[super client] --chat storage--- s
010[super client] --chat storage--- s

s>server] === database